apiVersion: v1
kind: Service
metadata:
  name: rick-morty-api-service
  labels:
    app: rick-morty-api
    component: api
spec:
  selector:
    app: rick-morty-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    name: http
  type: LoadBalancer
