---
# ServiceMonitor defines how Prometheus should scrape metrics from our service
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rick-morty-api-monitor
  labels:
    app: rick-morty-api
    release: prometheus
spec:
  selector:
    matchLabels:
      app: rick-morty-api
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'rickmorty_.*'
      action: keep
  namespaceSelector:
    matchNames:
    - default
---
# PrometheusRule defines alerting rules for our API
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rick-morty-api-alerts
  labels:
    app: rick-morty-api
    prometheus: kube-prometheus
    role: alert-rules
spec:
  groups:
  - name: rick-morty-api
    rules:
    - alert: RickMortyApiHighErrorRate
      expr: sum(rate(rickmorty_http_request_duration_seconds_count{status_code=~"5.."}[5m])) / sum(rate(rickmorty_http_request_duration_seconds_count[5m])) > 0.05
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High error rate on Rick and Morty API"
        description: "Error rate is above 5% for 5 minutes: {{ $value | humanizePercentage }}"
    
    - alert: RickMortyApiHighLatency
      expr: histogram_quantile(0.95, sum(rate(rickmorty_http_request_duration_seconds_bucket[5m])) by (le, endpoint)) > 1.0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High latency on Rick and Morty API"
        description: "95th percentile of request duration is above 1s for endpoint {{ $labels.endpoint }}"
    
    - alert: RickMortyApiHighRateLimitReached
      expr: sum(increase(rickmorty_rate_limit_reached_total[1h])) > 10
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "Rate limit reached frequently"
        description: "Rate limit reached more than 10 times in the last hour"
    
    - alert: RickMortyApiLowCacheHitRate
      expr: sum(rate(rickmorty_cache_hit_total[5m])) / (sum(rate(rickmorty_cache_hit_total[5m])) + sum(rate(rickmorty_cache_miss_total[5m]))) < 0.7
      for: 30m
      labels:
        severity: info
      annotations:
        summary: "Low cache hit rate"
        description: "Cache hit rate is below 70% for 30 minutes: {{ $value | humanizePercentage }}"
---
# Grafana dashboard configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: rick-morty-api-dashboard
  labels:
    grafana_dashboard: "true"
data:
  rick-morty-api-dashboard.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": null,
      "links": [],
      "panels": [
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Prometheus",
          "fieldConfig": {
            "defaults": {
              "custom": {}
            },
            "overrides": []
          },
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "hiddenSeries": false,
          "id": 1,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "dataLinks": []
          },
          "percentage": false,
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "sum(rate(rickmorty_http_request_duration_seconds_count[5m])) by (endpoint)",
              "interval": "",
              "legendFormat": "{{endpoint}}",
              "refId": "A"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "Request Rate by Endpoint",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": "Requests / sec",
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Prometheus",
          "fieldConfig": {
            "defaults": {
              "custom": {}
            },
            "overrides": []
          },
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 0
          },
          "hiddenSeries": false,
          "id": 2,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "dataLinks": []
          },
          "percentage": false,
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "histogram_quantile(0.95, sum(rate(rickmorty_http_request_duration_seconds_bucket[5m])) by (le, endpoint))",
              "interval": "",
              "legendFormat": "{{endpoint}} - p95",
              "refId": "A"
            },
            {
              "expr": "histogram_quantile(0.50, sum(rate(rickmorty_http_request_duration_seconds_bucket[5m])) by (le, endpoint))",
              "interval": "",
              "legendFormat": "{{endpoint}} - p50",
              "refId": "B"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "Request Duration",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "s",
              "label": "Duration",
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "aliasColors": {
            "Errors": "red",
            "Success": "green"
          },
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Prometheus",
          "fieldConfig": {
            "defaults": {
              "custom": {}
            },
            "overrides": []
          },
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 8
          },
          "hiddenSeries": false,
          "id": 3,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "dataLinks": []
          },
          "percentage": false,
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": true,
          "steppedLine": false,
          "targets": [
            {
              "expr": "sum(rate(rickmorty_http_request_duration_seconds_count{status_code=~\"2..\"}[5m]))",
              "interval": "",
              "legendFormat": "Success",
              "refId": "A"
            },
            {
              "expr": "sum(rate(rickmorty_http_request_duration_seconds_count{status_code=~\"[45]..\"}[5m]))",
              "interval": "",
              "legendFormat": "Errors",
              "refId": "B"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "Success vs Errors Rate",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": "Requests / sec",
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "aliasColors": {
            "Hits": "green",
            "Misses": "red"
          },
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Prometheus",
          "fieldConfig": {
            "defaults": {
              "custom": {}
            },
            "overrides": []
          },
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 8
          },
          "hiddenSeries": false,
          "id": 4,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "dataLinks": []
          },
          "percentage": false,
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": true,
          "steppedLine": false,
          "targets": [
            {
              "expr": "sum(rate(rickmorty_cache_hit_total[5m]))",
              "interval": "",
              "legendFormat": "Hits",
              "refId": "A"
            },
            {
              "expr": "sum(rate(rickmorty_cache_miss_total[5m]))",
              "interval": "",
              "legendFormat": "Misses",
              "refId": "B"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "Cache Hit/Miss Rate",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": "Rate",
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              

